@host = http://localhost:8080

### GET - Listar todas as empresas
GET {{host}}/empresas

### GET - Obter empresa por ID 
GET {{host}}/empresas/1

### POST - Criar nova empresa 
POST {{host}}/empresas
Content-Type: application/json

{
    "nomeFantasia": "Tech Solutions S.A.",
    "cnpj": "11.222.333/0001-44",
    "email": "contato@techsolutions.com",
    "endereco": "Av. Paulista, 1000",
    "descricao": "Empresa de consultoria em TI."
}

### PUT - Atualizar empresa com ID 
PUT {{host}}/empresas/1
Content-Type: application/json

{
    "nomeFantasia": "Tech Solutions & Inovação S.A.",
    "cnpj": "11.222.333/0001-44",
    "email": "contato@techsolutions.com",
    "endereco": "Av. Paulista, 1000, 10º Andar",
    "descricao": "Empresa líder em consultoria e desenvolvimento de software."
}

### DELETE - Deletar empresa com ID (ex: 3)
DELETE {{host}}/empresas/2