@host = http://localhost:8080

### GET - Listar todos os estudantes
GET {{host}}/estudantes

### GET - Obter estudante por ID 
GET {{host}}/estudantes/1

### POST - Criar novo estudante 
POST {{host}}/estudantes
Content-Type: application/json

{
    "nome": "Carla Mendes",
    "email": "carla.mendes@email.com",
    "anoIngresso": 2022
}

### PUT - Atualizar estudante com ID 
PUT {{host}}/estudantes/1
Content-Type: application/json

{
    "nome": "Carla Mendes Souza",
    "email": "carla.souza@novoemail.com",
    "anoIngresso": 2022
}

### PUT - Associar Áreas de Interesse a um Estudante
PUT {{host}}/estudantes/1
Content-Type: application/json

{
    "nome": "Carla Mendes Souza",
    "email": "carla.souza@novoemail.com",
    "anoIngresso": 2022,
    "areasDeInteresse": [
        { "id": 1 },
        { "id": 2 }
    ]
}


### DELETE - Deletar estudante com ID (ex: 2)
DELETE {{host}}/estudantes/2