@host = http://localhost:8080

### GET - Listar todas as vagas
GET {{host}}/vagas

### GET - Obter vaga por ID
GET {{host}}/vagas/1

### POST - Criar nova vaga
POST {{host}}/vagas
Content-Type: application/json

{
    "titulo": "Desenvolvedor Backend Java",
    "descricao": "Atuação em projetos com Spring Boot e microsserviços.",
    "dataPublicacao": "2025-11-01",
    "ativo": true,
    "empresa": {
        "id": 1
    }
}

### PUT - Atualizar vaga com ID
PUT {{host}}/vagas/1
Content-Type: application/json

{
    "titulo": "Desenvolvedor Backend Java (Foco em Cloud)",
    "descricao": "Atuação em projetos com Spring Boot e microsserviços AWS/Azure.",
    "dataPublicacao": "2025-11-01",
    "ativo": true,
    "empresa": {
        "id": 1
    }
}

### DELETE - Deletar vaga com ID
DELETE {{host}}/vagas/2